name: ci

on:
  push:
    branches:
      - "main"

env:
  TEST_TAG: aleden22/jove:test
  LATEST_TAG: aleden22/jove:latest

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Clear docker data
        shell: bash
        run: |
          sudo docker image prune --all --force
      -
        name: Stop docker
        shell: bash
        run: |
          sudo service docker stop
      -
        name: Create mount dir
        shell: bash
        run: |
          sudo mkdir /x
      -
        name: Maximize build space
        uses: jove-decompiler/maximize-build-space@master
        with:
          root-reserve-mb: 4096
          swap-size-mb: 2048
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
          remove-codeql: true
          overprovision-lvm: true
          remove-docker-images: false # we did this ourselves
          build-mount-path: '/x'
      -
        name: Fix up directories
        shell: bash
        run: |
          sudo mkdir /x/{docker,buildkit}
          sudo chmod 0777 /x/{docker,buildkit}

          sudo mkdir -p /var/lib/{docker,buildkit}

          sudo mount --bind /x/docker /var/lib/docker
          sudo mount --bind /x/buildkit /var/lib/buildkit

          mount | column -t
      -
        name: Start docker
        shell: bash
        run: |
          sudo service docker start
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
            submodules: true
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and export to Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}
      -
        name: Test
        run: |
          docker run --rm ${{ env.TEST_TAG }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ env.LATEST_TAG }}
